services:
  php-7.3:
    image: ghcr.io/markmetcalfe/docker-dev-php73
    container_name: totara_php73
    restart: ${RESTART_POLICY:-no}
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-7.3
      TZ: ${TIME_ZONE}
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    depends_on:
      - php-7.3-debug
    networks:
      - totara

  php-7.3-debug:
    image: ghcr.io/markmetcalfe/docker-dev-php73
    container_name: totara_php73_debug
    restart: ${RESTART_POLICY:-no}
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-7.3-debug
      TZ: ${TIME_ZONE}
      XDEBUG_CONFIG: client_host=${HOST_IP} log_level=0
      XDEBUG_MODE: debug
      XDEBUG_SESSION: totara73
      PHP_IDE_CONFIG: serverName=totara73
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    networks:
      - totara

  php-7.3-cron:
    image: ghcr.io/markmetcalfe/docker-dev-php73
    container_name: totara_php73_cron
    restart: ${RESTART_POLICY:-no}
    entrypoint: ["/cron-entrypoint.sh"]
    environment:
      TZ: ${TIME_ZONE}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./php/includes:/var/www/totara/includes
      - ./cron.d:/etc/cron.d
    networks:
      - totara

  php-7.4:
    image: ghcr.io/markmetcalfe/docker-dev-php74
    container_name: totara_php74
    restart: ${RESTART_POLICY:-no}
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-7.4
      TZ: ${TIME_ZONE}
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    depends_on:
      - php-7.4-debug
    networks:
      - totara

  php-7.4-debug:
    image: ghcr.io/markmetcalfe/docker-dev-php74
    container_name: totara_php74_debug
    restart: ${RESTART_POLICY:-no}
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-7.4-debug
      TZ: ${TIME_ZONE}
      XDEBUG_CONFIG: client_host=${HOST_IP} log_level=0
      XDEBUG_MODE: debug
      XDEBUG_SESSION: totara74
      PHP_IDE_CONFIG: serverName=totara74
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    networks:
      - totara

  php-7.4-cron:
    image: ghcr.io/markmetcalfe/docker-dev-php74
    container_name: totara_php74_cron
    restart: ${RESTART_POLICY:-no}
    entrypoint: ["/cron-entrypoint.sh"]
    environment:
      TZ: ${TIME_ZONE}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./php/includes:/var/www/totara/includes
      - ./cron.d:/etc/cron.d
    networks:
      - totara

  php-8.0:
    image: ghcr.io/markmetcalfe/docker-dev-php80
    container_name: totara_php80
    restart: ${RESTART_POLICY:-no}
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-8.0
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    depends_on:
      - php-8.0-debug
    networks:
      - totara

  php-8.0-debug:
    image: ghcr.io/markmetcalfe/docker-dev-php80-debug
    container_name: totara_php80_debug
    restart: ${RESTART_POLICY:-no}
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-8.0-debug
      TZ: ${TIME_ZONE}
      XDEBUG_CONFIG: client_host=${HOST_IP} log_level=0
      XDEBUG_MODE: debug
      XDEBUG_SESSION: totara80
      PHP_IDE_CONFIG: serverName=totara80
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    networks:
      - totara

  php-8.0-cron:
    image: ghcr.io/markmetcalfe/docker-dev-php80
    container_name: totara_php80_cron
    restart: ${RESTART_POLICY:-no}
    entrypoint: ["/cron-entrypoint.sh"]
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./php/includes:/var/www/totara/includes
      - ./cron.d:/etc/cron.d
    networks:
      - totara

  php-8.1:
    image: ghcr.io/markmetcalfe/docker-dev-php81
    container_name: totara_php81
    restart: ${RESTART_POLICY:-no}
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-8.1
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    depends_on:
      - php-8.1-debug
    networks:
      - totara

  php-8.1-cron:
    image: ghcr.io/markmetcalfe/docker-dev-php81
    container_name: totara_php81_cron
    restart: ${RESTART_POLICY:-no}
    entrypoint: ["/cron-entrypoint.sh"]
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./php/includes:/var/www/totara/includes
      - ./cron.d:/etc/cron.d
    networks:
      - totara

  php-8.1-debug:
    image: ghcr.io/markmetcalfe/docker-dev-php81
    container_name: totara_php81_debug
    restart: ${RESTART_POLICY:-no}
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-8.1-debug
      TZ: ${TIME_ZONE}
      XDEBUG_CONFIG: client_host=${HOST_IP} log_level=0
      XDEBUG_MODE: debug
      XDEBUG_SESSION: totara81
      PHP_IDE_CONFIG: serverName=totara81
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    networks:
      - totara

  php-8.2:
    image: ghcr.io/markmetcalfe/docker-dev-php82
    container_name: totara_php82
    restart: ${RESTART_POLICY:-no}
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-8.2
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    depends_on:
      - php-8.2-debug
    networks:
      - totara

  php-8.2-cron:
    image: ghcr.io/markmetcalfe/docker-dev-php82
    container_name: totara_php82_cron
    restart: ${RESTART_POLICY:-no}
    entrypoint: ["/cron-entrypoint.sh"]
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./php/includes:/var/www/totara/includes
      - ./cron.d:/etc/cron.d
    networks:
      - totara

  php-8.2-debug:
    image: ghcr.io/markmetcalfe/docker-dev-php82
    container_name: totara_php82_debug
    restart: ${RESTART_POLICY:-no}
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-8.2-debug
      TZ: ${TIME_ZONE}
      XDEBUG_CONFIG: client_host=${HOST_IP} log_level=0
      XDEBUG_MODE: debug
      XDEBUG_SESSION: totara82
      PHP_IDE_CONFIG: serverName=totara82
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    networks:
      - totara

  php-8.3:
    image: ghcr.io/markmetcalfe/docker-dev-php83
    container_name: totara_php83
    restart: ${RESTART_POLICY:-no}
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-8.3
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    depends_on:
      - php-8.3-debug
    networks:
      - totara

  php-8.3-cron:
    image: ghcr.io/markmetcalfe/docker-dev-php83
    container_name: totara_php83_cron
    restart: ${RESTART_POLICY:-no}
    entrypoint: ["/cron-entrypoint.sh"]
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./php/includes:/var/www/totara/includes
      - ./cron.d:/etc/cron.d
    networks:
      - totara

  php-8.3-debug:
    image: ghcr.io/markmetcalfe/docker-dev-php83
    container_name: totara_php83_debug
    restart: ${RESTART_POLICY:-no}
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-8.3-debug
      TZ: ${TIME_ZONE}
      XDEBUG_CONFIG: client_host=${HOST_IP} log_level=0
      XDEBUG_MODE: debug
      XDEBUG_SESSION: totara83
      PHP_IDE_CONFIG: serverName=totara83
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    networks:
      - totara

  php-8.4:
    image: ghcr.io/markmetcalfe/docker-dev-php84
    container_name: totara_php84
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-8.4
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    depends_on:
      - php-8.4-debug
    networks:
      - totara

  php-8.4-cron:
    image: ghcr.io/markmetcalfe/docker-dev-php84
    container_name: totara_php84_cron
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./php/includes:/var/www/totara/includes
      - ./cron.d:/etc/cron.d
    networks:
      - totara

  php-8.4-debug:
    image: ghcr.io/markmetcalfe/docker-dev-php84
    container_name: totara_php84_debug
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-8.4-debug
      TZ: ${TIME_ZONE}
      XDEBUG_CONFIG: client_host=${HOST_IP} log_level=0
      XDEBUG_MODE: debug
      XDEBUG_SESSION: totara84
      PHP_IDE_CONFIG: serverName=totara84
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    networks:
      - totara

  # php-X.X: ...
  # php-X.X-cron: ...
  # php-X.X-debug: ...

  # When adding a new PHP container, make sure you also add entries in:
  # compose/build.yml, compose/sync.yml, .github/workflows/build-php.yml

volumes:
  totara-data:
  coverage-report:
  bash-history:
  zsh-history:
