name: Build docker images

on:
  release:
    types:
      - created
  push: # TODO: Remove

jobs:
  build-base-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # - image: apache
          #   context: ./apache
          - image: nginx
            context: ./nginx
          # - image: mssql2017
          #   context: ./mssql
          #   dockerfile: 2017/Dockerfile
          # - image: mssql2019
          #   context: ./mssql
          #   dockerfile: 2019/Dockerfile
          # - image: mssql2022
          #   context: ./mssql
          #   dockerfile: 2022/Dockerfile
          # - image: php53
          #   context: ./php/php53
          # - image: php54
          #   context: ./php/php54
          # - image: php55
          #   context: ./php/php55
          - image: php56
            context: ./php/php56
          # - image: php70
          #   context: ./php/php70
          # - image: php71
          #   context: ./php/php71
          # - image: php72
          #   context: ./php/php72
          # - image: php73
          #   context: ./php/php73
          # - image: php74
          #   context: ./php/php74
          # - image: php80
          #   context: ./php/php80
          # - image: php81
          #   context: ./php/php81
          # - image: php82
          #   context: ./php/php82
          # - image: php83
          #   context: ./php/php83

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
      - name: Log in to the Container registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        with:
          images: ghcr.io/${{ github.repository_owner }}/docker-dev-${{ matrix.image }}
      - name: Set up QEMU (to support building for both amd64 and arm64)
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1
        with:
          platforms: linux/amd64,linux/arm64
      - name: Build and push images
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/${{ matrix.dockerfile || 'Dockerfile' }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
