name: Build Apache image

on:
  release:
    types:
      - created
  pull_request:
    branches:
      - master
      - develop
    paths:
      - apache/**
      - ./.github/workflows/build-image.yml

jobs:
  build-apache-image:
    name: Build Apache image
    uses: ./.github/workflows/build-image.yml
    with:
      image: apache
      context: ./apache
      push: ${{ github.event_name == 'release' }}
    secrets: inherit
