name: Conventional Commit Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Validate commits are Conventional Commits
        uses: ./.github/actions/cc-checker
        with:
          commit-types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
          github-token: ${{ secrets.GITHUB_TOKEN }}
